#!/bin/sh

ENABLED=yes
PROCS=ss-server
ARGS="-c /opt/etc/shadowsocks/shadowsocks.json"
PREARGS="nohup"
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[ -z "$(which $PROCS)" ] && exit 0

. /opt/etc/init.d/rc.func
