#!/bin/sh

ENABLED=yes
PROCS=tpws
ARGS="--bind-addr=$(nvram get lan_ipaddr) --port=1010 --split-http-req=host --daemon"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
